# Generated by Django 4.1.4 on 2023-01-17 15:19

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Mobiles')),
                ('screan', models.CharField(max_length=250)),
                ('mobile_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('mobile_color2', colorfield.fields.ColorField(default='#FC0000', image_field=None, max_length=18, samples=None)),
                ('mobile_color3', colorfield.fields.ColorField(default='#FB0000', image_field=None, max_length=18, samples=None)),
                ('mobile_color4', colorfield.fields.ColorField(default='#FA0000', image_field=None, max_length=18, samples=None)),
                ('coverage', models.CharField(max_length=250)),
                ('camera', models.CharField(max_length=250)),
                ('core', models.CharField(max_length=250)),
                ('battery', models.CharField(max_length=250)),
                ('front', models.CharField(max_length=250)),
                ('name', models.CharField(default=False, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_orderd', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=300, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=250)),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Covergimage', models.ImageField(null=True, upload_to='placeToUpload')),
                ('Battrayimage', models.ImageField(null=True, upload_to='placeToUpload')),
                ('Coreimage', models.ImageField(null=True, upload_to='placeToUpload')),
                ('Frontimage', models.ImageField(null=True, upload_to='placeToUpload')),
                ('Cameraimage', models.ImageField(null=True, upload_to='placeToUpload')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('size', models.FloatField(default=None)),
                ('color', models.CharField(default=None, max_length=250)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('screan', models.CharField(max_length=250)),
                ('mobile_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('mobile_color2', colorfield.fields.ColorField(default='#FC0000', image_field=None, max_length=18, samples=None)),
                ('mobile_color3', colorfield.fields.ColorField(default='#FB0000', image_field=None, max_length=18, samples=None)),
                ('mobile_color4', colorfield.fields.ColorField(default='#FA0000', image_field=None, max_length=18, samples=None)),
                ('coverage', models.CharField(max_length=250)),
                ('camera', models.CharField(max_length=250)),
                ('core', models.CharField(max_length=250)),
                ('battery', models.CharField(max_length=250)),
                ('front', models.CharField(max_length=250)),
                ('Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('ProductImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productsimages')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
